// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

type Entry struct {
	ID      int64   `json:"id"`
	Title   string  `json:"title"`
	Link    string  `json:"link"`
	Date    int64   `json:"date"`
	IsRead  bool    `json:"is_read"`
	IDFeed  int64   `json:"id_feed"`
	Content *string `json:"content"`
}

type Feed struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
