// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package data

import (
	"context"
)

const getEntries = `-- name: GetEntries :many
SELECT id, title, link, date, is_read, id_feed, content FROM entry WHERE id_feed = ?1 AND date >= ?2 AND date < ?3 ORDER BY date DESC
`

type GetEntriesParams struct {
	FeedID   int64 `json:"feed_id"`
	FromDate int64 `json:"from_date"`
	ToDate   int64 `json:"to_date"`
}

func (q *Queries) GetEntries(ctx context.Context, arg GetEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, getEntries, arg.FeedID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Link,
			&i.Date,
			&i.IsRead,
			&i.IDFeed,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeeds = `-- name: GetFeeds :many
SELECT id, name FROM feed
`

func (q *Queries) GetFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEntryAsRead = `-- name: MarkEntryAsRead :exec
UPDATE entry SET is_read = 1 WHERE id = ?1
`

func (q *Queries) MarkEntryAsRead(ctx context.Context, entryID int64) error {
	_, err := q.db.ExecContext(ctx, markEntryAsRead, entryID)
	return err
}
